version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11.0.1-jdk

    working_directory: ~/springframeworkguru

    steps:
      # git pull
      - checkout

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: springframeworkguru-{{ checksum "pom.xml" }}

      # package into a jar
      - run: mvn test
      - run: mvn package
      - run: mvn verify
      - run: mvn install

      # store raw contents of src code
      - store_artifacts:
          path: target/classes
          destination: springframeworkguru
